spring:
  application:
    name: chess
  datasource:
    # 47.104.224.71
    url: jdbc:mysql://localhost:3306/chess?useSSL=false&serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    username: chess
    password: aDnv129.23Qkf2..23pK
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none